name:                aoc2025
version:             0.1.0.0
github:              "jahaynes/ advent-of-code-2025"
license:             BSD-3-Clause
author:              "John Haynes"
maintainer:          "john.andrew.haynes@gmail.com"
copyright:           "2025 John Haynes"
description:         Advent of code 2025

dependencies:
- base

ghc-options:
- -O2
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src/Common
  exposed-modules:
    - Combinators
    - Parser

executables:

  Day01:
    main:           Main.hs
    source-dirs:    src/Day01
    default-extensions:
      - MultiWayIf

  Day02:
    main:           Main.hs
    source-dirs:    src/Day02
    default-extensions:
      - BangPatterns
      - ScopedTypeVariables
    dependencies:
      - containers
      - split

  Day03:
    main:           Main.hs
    source-dirs:    src/Day03
    default-extensions:
      - ScopedTypeVariables

  Day04:
    main:           Main.hs
    source-dirs:    src/Day04
    default-extensions:
      - TupleSections
    dependencies:
      - containers

  Day05:
      main:           Main.hs
      source-dirs:    src/Day05

  Day06:
      main:           Main.hs
      source-dirs:    src/Day06
      dependencies:
        - aoc2025
